fos_rest:
  view:
    view_response_listener:  true
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.controller:showAction'
